  </div>
</div>
<!-- BEGIN CHAT --> 
<div class="chat-window-wrapper">
	<div id="main-chat-wrapper" class="inner-content">
        <div class="chat-window-wrapper scroller scrollbar-dynamic" id="chat-users" >
            <div class="chat-header">	
            <div class="pull-left">
                <input type="text" placeholder="search">
            </div>		
                <div class="pull-right">
                    <a href="#" class="" ><div class="iconset top-settings-dark "></div> </a>
                </div>			
            </div>	
            <div class="side-widget">
               <div class="side-widget-title">group chats</div>
                <div class="side-widget-content">
                 <div id="groups-list">
                    <ul class="groups" >
                        <li><a href="#"><div class="status-icon green"></div>Office work</a></li>
                        <li><a href="#"><div class="status-icon green"></div>Personal vibes</a></li>
                    </ul>
                </div>
                </div>
            </div>
            <div class="side-widget fadeIn">
               <div class="side-widget-title">favourites</div>
               <div id="favourites-list">
                <div class="side-widget-content" >
                    <div class="user-details-wrapper active" data-chat-status="online" data-chat-user-pic="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-chat-user-pic-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" data-user-name="Jane Smith">
                        <div class="user-profile">
                            <img src="<?= Core::absURL() ?>assets/img/profiles/d.jpg"  alt="" data-src="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-src-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" width="35" height="35">
                        </div>
                        <div class="user-details">
                            <div class="user-name">
                            Jane Smith
                            </div>
                            <div class="user-more">
                            Hello you there?
                            </div>
                        </div>
                        <div class="user-details-status-wrapper">
                            <span class="badge badge-important">3</span>
                        </div>
                        <div class="user-details-count-wrapper">
                            <div class="status-icon green"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>	
                    <div class="user-details-wrapper" data-chat-status="busy" data-chat-user-pic="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-chat-user-pic-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" data-user-name="David Nester">
                        <div class="user-profile">
                            <img src="<?= Core::absURL() ?>assets/img/profiles/c.jpg"  alt="" data-src="<?= Core::absURL() ?>assets/img/profiles/c.jpg" data-src-retina="<?= Core::absURL() ?>assets/img/profiles/c2x.jpg" width="35" height="35">
                        </div>
                        <div class="user-details">
                            <div class="user-name">
                            David Nester
                            </div>
                            <div class="user-more">
                            Busy, Do not disturb
                            </div>
                        </div>
                        <div class="user-details-status-wrapper">
                            <div class="clearfix"></div>
                        </div>
                        <div class="user-details-count-wrapper">
                            <div class="status-icon red"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>					
                </div>
                </div>
            </div>
            <div class="side-widget">
               <div class="side-widget-title">more friends</div>
                 <div class="side-widget-content" id="friends-list">
                    <div class="user-details-wrapper" data-chat-status="online" data-chat-user-pic="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-chat-user-pic-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" data-user-name="Jane Smith">
                        <div class="user-profile">
                            <img src="<?= Core::absURL() ?>assets/img/profiles/d.jpg"  alt="" data-src="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-src-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" width="35" height="35">
                        </div>
                        <div class="user-details">
                            <div class="user-name">
                            Jane Smith
                            </div>
                            <div class="user-more">
                            Hello you there?
                            </div>
                        </div>
                        <div class="user-details-status-wrapper">

                        </div>
                        <div class="user-details-count-wrapper">
                            <div class="status-icon green"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>	
                    <div class="user-details-wrapper" data-chat-status="busy" data-chat-user-pic="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-chat-user-pic-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" data-user-name="David Nester">
                        <div class="user-profile">
                            <img src="<?= Core::absURL() ?>assets/img/profiles/h.jpg"  alt="" data-src="<?= Core::absURL() ?>assets/img/profiles/h.jpg" data-src-retina="<?= Core::absURL() ?>assets/img/profiles/h2x.jpg" width="35" height="35">
                        </div>
                        <div class="user-details">
                            <div class="user-name">
                            David Nester
                            </div>
                            <div class="user-more">
                            Busy, Do not disturb
                            </div>
                        </div>
                        <div class="user-details-status-wrapper">
                            <div class="clearfix"></div>
                        </div>
                        <div class="user-details-count-wrapper">
                            <div class="status-icon red"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>		
                    <div class="user-details-wrapper" data-chat-status="online" data-chat-user-pic="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-chat-user-pic-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" data-user-name="Jane Smith">
                        <div class="user-profile">
                            <img src="<?= Core::absURL() ?>assets/img/profiles/c.jpg"  alt="" data-src="<?= Core::absURL() ?>assets/img/profiles/c.jpg" data-src-retina="<?= Core::absURL() ?>assets/img/profiles/c2x.jpg" width="35" height="35">
                        </div>
                        <div class="user-details">
                            <div class="user-name">
                            Jane Smith
                            </div>
                            <div class="user-more">
                            Hello you there?
                            </div>
                        </div>
                        <div class="user-details-status-wrapper">

                        </div>
                        <div class="user-details-count-wrapper">
                            <div class="status-icon green"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>	
                    <div class="user-details-wrapper" data-chat-status="busy" data-chat-user-pic="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-chat-user-pic-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" data-user-name="David Nester">
                        <div class="user-profile">
                            <img src="<?= Core::absURL() ?>assets/img/profiles/h.jpg"  alt="" data-src="<?= Core::absURL() ?>assets/img/profiles/h.jpg" data-src-retina="<?= Core::absURL() ?>assets/img/profiles/h2x.jpg" width="35" height="35">
                        </div>
                        <div class="user-details">
                            <div class="user-name">
                            David Nester
                            </div>
                            <div class="user-more">
                            Busy, Do not disturb
                            </div>
                        </div>
                        <div class="user-details-status-wrapper">
                            <div class="clearfix"></div>
                        </div>
                        <div class="user-details-count-wrapper">
                            <div class="status-icon red"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>				
                </div>		
            </div>
        </div>

        <div class="chat-window-wrapper" id="messages-wrapper" style="display:none">
        <div class="chat-header">	
            <div class="pull-left">
                <input type="text" placeholder="search">
            </div>		
                <div class="pull-right">
                    <a href="#" class="" ><div class="iconset top-settings-dark "></div> </a>
                </div>					
            </div>
        <div class="clearfix"></div>	
        <div class="chat-messages-header">
        <div class="status online"></div><span class="semi-bold">Jane Smith(Typing..)</span>
        <a href="#" class="chat-back"><i class="icon-custom-cross"></i></a>
        </div>
        <div class="chat-messages scrollbar-dynamic clearfix">
            <div class="inner-scroll-content clearfix">
            <div class="sent_time">Yesterday 11:25pm</div>
            <div class="user-details-wrapper " >
                <div class="user-profile">
                    <img src="<?= Core::absURL() ?>assets/img/profiles/d.jpg"  alt="" data-src="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-src-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" width="35" height="35">
                </div>
                <div class="user-details">
                  <div class="bubble">	
                        Hello, You there?
                   </div>
                </div>					
                <div class="clearfix"></div>
               <div class="sent_time off">Yesterday 11:25pm</div>
            </div>		
            <div class="user-details-wrapper ">
                <div class="user-profile">
                    <img src="<?= Core::absURL() ?>assets/img/profiles/d.jpg"  alt="" data-src="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-src-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" width="35" height="35">
                </div>
                <div class="user-details">
                  <div class="bubble">	
                        How was the meeting?
                   </div>
                </div>					
                <div class="clearfix"></div>
                <div class="sent_time off">Yesterday 11:25pm</div>
            </div>
            <div class="user-details-wrapper ">
                <div class="user-profile">
                    <img src="<?= Core::absURL() ?>assets/img/profiles/d.jpg"  alt="" data-src="<?= Core::absURL() ?>assets/img/profiles/d.jpg" data-src-retina="<?= Core::absURL() ?>assets/img/profiles/d2x.jpg" width="35" height="35">
                </div>
                <div class="user-details">
                  <div class="bubble">	
                        Let me know when you free
                   </div>
                </div>					
                <div class="clearfix"></div>
                <div class="sent_time off">Yesterday 11:25pm</div>
            </div>
            <div class="sent_time ">Today 11:25pm</div>
            <div class="user-details-wrapper pull-right">
                <div class="user-details">
                  <div class="bubble sender">	
                        Let me know when you free
                   </div>
                </div>					
                <div class="clearfix"></div>
                <div class="sent_time off">Sent On Tue, 2:45pm</div>
            </div>		
        </div>
        </div>
        <div class="chat-input-wrapper" style="display:none">
            <textarea id="chat-message-input" rows="1" placeholder="Type your message"></textarea>
        </div>
        <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- END CHAT -->		  
</div>

<!-- END CONTAINER -->
<!-- BEGIN CORE JS FRAMEWORK-->
    
<!--[if lt IE 9]>
<script src="<?= Core::absURL() ?>assets/plugins/respond.js"></script>
<![endif]-->

<script src="<?= Core::absURL() ?>assets/plugins/jquery-1.8.3.min.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/boostrapv3/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/breakpoints.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-unveil/jquery.unveil.min.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-block-ui/jqueryblockui.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-lazyload/jquery.lazyload.min.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js" type="text/javascript"></script>
<!-- END CORE JS FRAMEWORK -->
<!-- BEGIN PAGE LEVEL JS -->
<script src="<?= Core::absURL() ?>assets/plugins/jquery-slider/jquery.sidr.min.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/pace/pace.min.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-numberAnimate/jquery.animateNumbers.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-ricksaw-chart/js/raphael-min.js"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-ricksaw-chart/js/d3.v2.js"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-ricksaw-chart/js/rickshaw.min.js"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-sparkline/jquery-sparkline.js"></script>
<script src="<?= Core::absURL() ?>assets/plugins/skycons/skycons.js"></script>
<script src="<?= Core::absURL() ?>assets/plugins/owl-carousel/owl.carousel.min.js" type="text/javascript"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-gmap/gmaps.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/Mapplic/js/jquery.easing.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/Mapplic/js/jquery.mousewheel.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/Mapplic/js/hammer.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/Mapplic/mapplic/mapplic.js" type="text/javascript"></script>
    
<script src="<?= Core::absURL() ?>assets/plugins/jquery-flot/jquery.flot.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-flot/jquery.flot.resize.min.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/plugins/jquery-metrojs/MetroJs.min.js" type="text/javascript" ></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN CORE TEMPLATE JS -->
<script src="<?= Core::absURL() ?>assets/js/core.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/js/chat.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/js/demo.js" type="text/javascript"></script>
<script src="<?= Core::absURL() ?>assets/js/dashboard_v2.js" type="text/javascript"></script>
<script type="text/javascript">
        $(document).ready(function () {
            $(".live-tile,.flip-list").liveTile();
        });
</script>

<!-- END CORE TEMPLATE JS -->
</body>
</html>